package com.batmad.birddefense.core.States;

/**
 * Created by tm on 16.02.2016.
 */
public class Levels {
    public static final int NUMBER_OF_LEVELS = 15;
    public PlayStateOptions[] levels;
    public PlayStateOptions level1, level2, level3, level4, level5, level6, level7, level8, level9, level10, level11, level12, level13, level14, level15;

    public Levels() {
        levels = new PlayStateOptions[NUMBER_OF_LEVELS];
        level1 = new PlayStateOptions(1,1);
        level1.put(0, PlayStateOptions.Bird.Bird, 25);
        levels[0] = level1;

        level2 = new PlayStateOptions(2,2);
        level2.put(0, PlayStateOptions.Bird.Bird, 10);
        level2.put(1, PlayStateOptions.Bird.Bird, 5);
        level2.put(1, PlayStateOptions.Bird.SlowBird, 3);
        level2.put(1, PlayStateOptions.Bird.Bird2, 5);
        level2.put(1, PlayStateOptions.Bird.SlowBird2, 4);
        level2.put(1, PlayStateOptions.Bird.Bird3, 6);
        levels[1] = level2;

        level3 = new PlayStateOptions(3,3);
        level3.put(0, PlayStateOptions.Bird.Bird, 20);
        level3.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level3.put(0, PlayStateOptions.Bird.Bird2, 7);
        level3.put(1, PlayStateOptions.Bird.Bird, 9);
        level3.put(1, PlayStateOptions.Bird.SlowBird, 2);
        level3.put(1, PlayStateOptions.Bird.Bird2, 6);
        level3.put(1, PlayStateOptions.Bird.SlowBird2, 2);
        level3.put(1, PlayStateOptions.Bird.FastBird, 4);
        level3.put(1, PlayStateOptions.Bird.SlowBird3, 3);
        level3.put(1, PlayStateOptions.Bird.Bird4, 10);
        level3.put(2, PlayStateOptions.Bird.Boss1, 1);
        levels[2] = level3;

        level4 = new PlayStateOptions(3,4);
        level4.put(0, PlayStateOptions.Bird.Bird, 10);
        level4.put(0, PlayStateOptions.Bird.SlowBird, 2);
        level4.put(0, PlayStateOptions.Bird.Bird2, 5);
        level4.put(0, PlayStateOptions.Bird.SlowBird2, 3);
        level4.put(0, PlayStateOptions.Bird.FastBird2, 4);
        level4.put(1, PlayStateOptions.Bird.FastBird, 5);
        level4.put(1, PlayStateOptions.Bird.SlowBird, 2);
        level4.put(1, PlayStateOptions.Bird.Bird2, 5);
        level4.put(1, PlayStateOptions.Bird.SlowBird2, 3);
        level4.put(1, PlayStateOptions.Bird.Bird2, 6);
        level4.put(2, PlayStateOptions.Bird.Bird, 15);
        level4.put(2, PlayStateOptions.Bird.SprintBird, 5);
        levels[3] = level4;

        level5 = new PlayStateOptions(3,5);
        level5.put(0, PlayStateOptions.Bird.Bird, 16);
        level5.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level5.put(0, PlayStateOptions.Bird.FastBird, 3);
        level5.put(0, PlayStateOptions.Bird.SprintBird, 1);
        level5.put(1, PlayStateOptions.Bird.Bird, 15);
        level5.put(1, PlayStateOptions.Bird.SprintBird, 2);
        level5.put(1, PlayStateOptions.Bird.SlowBird, 3);
        level5.put(1, PlayStateOptions.Bird.SprintBird2, 4);
        level5.put(1, PlayStateOptions.Bird.Bird, 10);
        level5.put(2, PlayStateOptions.Bird.Bird, 12);
        level5.put(2, PlayStateOptions.Bird.SlowBird, 3);
        level5.put(2, PlayStateOptions.Bird.Bird2, 10);
        level5.put(2, PlayStateOptions.Bird.SprintBird, 8);
        level5.put(2, PlayStateOptions.Bird.Bird3, 4);
        levels[4] = level5;

        level6 = new PlayStateOptions(3,6);
        level6.put(0, PlayStateOptions.Bird.Bird, 25);
        level6.put(0, PlayStateOptions.Bird.SlowBird, 2);
        level6.put(0, PlayStateOptions.Bird.Bird2, 15);
        level6.put(0, PlayStateOptions.Bird.SlowBird2, 3);
        level6.put(0, PlayStateOptions.Bird.FastBird, 5);
        level6.put(0, PlayStateOptions.Bird.BirdStupid, 2);
        level6.put(0, PlayStateOptions.Bird.SprintBird, 5);
        level6.put(0, PlayStateOptions.Bird.BirdStupid2, 3);
        level6.put(0, PlayStateOptions.Bird.Bird3, 10);
        level6.put(1, PlayStateOptions.Bird.Bird, 10);
        level6.put(1, PlayStateOptions.Bird.BirdStupid, 1);
        level6.put(1, PlayStateOptions.Bird.Bird2, 5);
        level6.put(1, PlayStateOptions.Bird.BirdStupid2, 1);
        level6.put(1, PlayStateOptions.Bird.SprintBird, 6);
        level6.put(1, PlayStateOptions.Bird.BirdStupid3, 2);
        level6.put(1, PlayStateOptions.Bird.Bird3, 10);
        level6.put(1, PlayStateOptions.Bird.BirdHealer, 3);
        level6.put(2, PlayStateOptions.Bird.Boss2, 1);
        levels[5] = level6;

        level7 = new PlayStateOptions(3,7);
        level7.put(0, PlayStateOptions.Bird.Bird, 10);
        level7.put(0, PlayStateOptions.Bird.BirdStupid, 1);
        level7.put(0, PlayStateOptions.Bird.SprintBird, 5);
        level7.put(0, PlayStateOptions.Bird.Bird2, 10);
        level7.put(0, PlayStateOptions.Bird.BirdStupid2, 1);
        level7.put(0, PlayStateOptions.Bird.SlowBird, 2);
        level7.put(0, PlayStateOptions.Bird.FastBird, 8);
        level7.put(0, PlayStateOptions.Bird.SlowBird2, 3);
        level7.put(0, PlayStateOptions.Bird.Bird3, 10);
        level7.put(1, PlayStateOptions.Bird.Bird, 20);
        level7.put(1, PlayStateOptions.Bird.SlowBird, 3);
        level7.put(1, PlayStateOptions.Bird.SprintBird, 7);
        level7.put(1, PlayStateOptions.Bird.BirdStupid, 2);
        level7.put(1, PlayStateOptions.Bird.Bird2, 10);
        level7.put(1, PlayStateOptions.Bird.BirdZerg, 5);
        level7.put(2, PlayStateOptions.Bird.Bird, 20);
        level7.put(2, PlayStateOptions.Bird.BirdZerg, 6);
        level7.put(2, PlayStateOptions.Bird.Bird2, 6);
        levels[6] = level7;

        level8 = new PlayStateOptions(3,8);
        level8.put(0, PlayStateOptions.Bird.Bird, 15);
        level8.put(0, PlayStateOptions.Bird.SlowBird, 2);
        level8.put(0, PlayStateOptions.Bird.Bird2, 10);
        level8.put(0, PlayStateOptions.Bird.SlowBird2, 3);
        level8.put(0, PlayStateOptions.Bird.SprintBird, 4);
        level8.put(0, PlayStateOptions.Bird.BirdStupid, 2);
        level8.put(0, PlayStateOptions.Bird.FastBird, 14);
        level8.put(0, PlayStateOptions.Bird.BirdStupid2, 2);
        level8.put(0, PlayStateOptions.Bird.Bird3, 4);
        level8.put(0, PlayStateOptions.Bird.FastBird2, 4);
        level8.put(0, PlayStateOptions.Bird.SprintBird2, 2);
        level8.put(1, PlayStateOptions.Bird.Bird, 10);
        level8.put(1, PlayStateOptions.Bird.SlowBird, 2);
        level8.put(1, PlayStateOptions.Bird.SprintBird, 6);
        level8.put(1, PlayStateOptions.Bird.SlowBird2, 2);
        level8.put(1, PlayStateOptions.Bird.Bird2, 4);
        level8.put(1, PlayStateOptions.Bird.SlowBird3, 2);
        level8.put(1, PlayStateOptions.Bird.Bird3, 4);
        level8.put(1, PlayStateOptions.Bird.BirdStupid, 1);
        level8.put(1, PlayStateOptions.Bird.Bird4, 4);
        level8.put(1, PlayStateOptions.Bird.BirdStupid2, 2);
        level8.put(1, PlayStateOptions.Bird.FastBird, 6);
        level8.put(1, PlayStateOptions.Bird.BirdStupid3, 3);
        level8.put(1, PlayStateOptions.Bird.Bird5, 6);
        level8.put(1, PlayStateOptions.Bird.FastBird2, 6);
        level8.put(1, PlayStateOptions.Bird.SprintBird2, 2);
        level8.put(1, PlayStateOptions.Bird.BirdZerg, 10);
        level8.put(1, PlayStateOptions.Bird.BirdHealer, 4);
        level8.put(2, PlayStateOptions.Bird.SprintBird, 10);
        level8.put(2, PlayStateOptions.Bird.BirdTeleport, 6);
        level8.put(2, PlayStateOptions.Bird.BirdZerg, 5);
        level8.put(2, PlayStateOptions.Bird.BirdTeleport2, 6);
        level8.put(2, PlayStateOptions.Bird.Bird, 8);
        level8.put(2, PlayStateOptions.Bird.BirdTeleport3, 6);
        level8.put(2, PlayStateOptions.Bird.BirdStupid, 2);
        level8.put(2, PlayStateOptions.Bird.Bird, 4);
        level8.put(2, PlayStateOptions.Bird.BirdStupid2, 3);
        level8.put(2, PlayStateOptions.Bird.Bird2, 4);
        level8.put(2, PlayStateOptions.Bird.SprintBird2, 2);
        level8.put(2, PlayStateOptions.Bird.FastBird, 6);
        level8.put(2, PlayStateOptions.Bird.BirdHealer, 4);
        levels[7] = level8;

        level9 = new PlayStateOptions(3,9);
        level9.put(0, PlayStateOptions.Bird.Bird, 15);
        level9.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level9.put(0, PlayStateOptions.Bird.Bird2, 6);
        level9.put(0, PlayStateOptions.Bird.BirdStupid, 1);
        level9.put(0, PlayStateOptions.Bird.Bird3, 4);
        level9.put(0, PlayStateOptions.Bird.BirdStupid2, 2);
        level9.put(0, PlayStateOptions.Bird.BirdTeleport, 3);
        level9.put(0, PlayStateOptions.Bird.FastBird, 13);
        level9.put(0, PlayStateOptions.Bird.SprintBird, 13);
        level9.put(0, PlayStateOptions.Bird.BirdTeleport2, 3);
        level9.put(1, PlayStateOptions.Bird.BirdZerg, 3);
        level9.put(1, PlayStateOptions.Bird.SlowBird, 3);
        level9.put(1, PlayStateOptions.Bird.BirdTeleport, 3);
        level9.put(1, PlayStateOptions.Bird.Bird, 5);
        level9.put(1, PlayStateOptions.Bird.BirdStupid, 2);
        level9.put(1, PlayStateOptions.Bird.Bird2, 5);
        level9.put(1, PlayStateOptions.Bird.BirdTeleport2, 3);
        level9.put(1, PlayStateOptions.Bird.BirdStupid2, 2);
        level9.put(1, PlayStateOptions.Bird.FastBird, 5);
        level9.put(1, PlayStateOptions.Bird.SprintBird, 1);
        level9.put(1, PlayStateOptions.Bird.Bird3, 3);
        level9.put(1, PlayStateOptions.Bird.SlowBird2, 3);
        level9.put(1, PlayStateOptions.Bird.FastBird2, 3);
        level9.put(1, PlayStateOptions.Bird.Bird4, 5);
        level9.put(1, PlayStateOptions.Bird.BirdTeleport3, 9);
        level9.put(1, PlayStateOptions.Bird.BirdHealer, 6);
        level9.put(1, PlayStateOptions.Bird.BirdZerg, 6);
        level9.put(2, PlayStateOptions.Bird.Boss3, 1);
        levels[8] = level9;

        level10 = new PlayStateOptions(3,10);
        level10.put(0, PlayStateOptions.Bird.Bird, 15);
        level10.put(0, PlayStateOptions.Bird.BirdTeleport, 1);
        level10.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level10.put(0, PlayStateOptions.Bird.FastBird, 2);
        level10.put(0, PlayStateOptions.Bird.BirdStupid, 2);
        level10.put(0, PlayStateOptions.Bird.SprintBird, 2);
        level10.put(0, PlayStateOptions.Bird.FastBird, 4);
        level10.put(0, PlayStateOptions.Bird.Bird2, 4);
        level10.put(1, PlayStateOptions.Bird.BirdAngry, 3);
        level10.put(1, PlayStateOptions.Bird.Bird, 5);
        level10.put(1, PlayStateOptions.Bird.BirdTeleport, 7);
        level10.put(1, PlayStateOptions.Bird.SprintBird, 5);
        level10.put(1, PlayStateOptions.Bird.BirdZerg, 7);
        level10.put(1, PlayStateOptions.Bird.BirdHealer, 3);
        level10.put(2, PlayStateOptions.Bird.Bird, 9);
        level10.put(2, PlayStateOptions.Bird.BirdAngry, 2);
        level10.put(2, PlayStateOptions.Bird.Bird2, 4);
        level10.put(2, PlayStateOptions.Bird.BirdStupid, 3);
        level10.put(2, PlayStateOptions.Bird.FastBird, 6);
        level10.put(2, PlayStateOptions.Bird.Bird3, 10);
        level10.put(2, PlayStateOptions.Bird.SprintBird, 4);
        level10.put(2, PlayStateOptions.Bird.BirdTeleport, 3);
        level10.put(2, PlayStateOptions.Bird.BirdAngry2, 2);
        level10.put(2, PlayStateOptions.Bird.SprintBird2, 6);
        level10.put(2, PlayStateOptions.Bird.BirdHealer, 6);
        level10.put(2, PlayStateOptions.Bird.BirdZerg, 8);
        levels[9] = level10;

        level11 = new PlayStateOptions(3,11);
        level11.put(0, PlayStateOptions.Bird.Bird, 10);
        level11.put(0, PlayStateOptions.Bird.FastBird, 10);
        level11.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level11.put(0, PlayStateOptions.Bird.BirdFire, 10);
        level11.put(0, PlayStateOptions.Bird.BirdStupid, 3);
        level11.put(0, PlayStateOptions.Bird.Bird2, 4);
        level11.put(0, PlayStateOptions.Bird.FastBird2, 4);
        level11.put(0, PlayStateOptions.Bird.BirdTeleport, 6);
        level11.put(1, PlayStateOptions.Bird.BirdFire, 10);
        level11.put(1, PlayStateOptions.Bird.Bird, 2);
        level11.put(1, PlayStateOptions.Bird.SlowBird, 2);
        level11.put(1, PlayStateOptions.Bird.Bird2, 2);
        level11.put(1, PlayStateOptions.Bird.BirdStupid, 2);
        level11.put(1, PlayStateOptions.Bird.FastBird, 2);
        level11.put(1, PlayStateOptions.Bird.SprintBird, 10);
        level11.put(1, PlayStateOptions.Bird.BirdAngry, 6);
        level11.put(1, PlayStateOptions.Bird.BirdHealer, 5);
        level11.put(1, PlayStateOptions.Bird.BirdZerg, 10);
        level11.put(2, PlayStateOptions.Bird.BirdFire, 10);
        level11.put(2, PlayStateOptions.Bird.BirdTeleport, 10);
        level11.put(2, PlayStateOptions.Bird.FastBird, 10);
        level11.put(2, PlayStateOptions.Bird.BirdStupid, 1);
        level11.put(2, PlayStateOptions.Bird.Bird, 5);
        level11.put(2, PlayStateOptions.Bird.BirdAngry, 8);
        level11.put(2, PlayStateOptions.Bird.BirdHealer, 5);
        level11.put(2, PlayStateOptions.Bird.BirdZerg, 15);
        levels[10] = level11;

        level12 = new PlayStateOptions(3,12);
        level12.put(0, PlayStateOptions.Bird.Bird, 10);
        level12.put(0, PlayStateOptions.Bird.SlowBird, 2);
        level12.put(0, PlayStateOptions.Bird.FastBird, 10);
        level12.put(0, PlayStateOptions.Bird.BirdFire, 10);
        level12.put(0, PlayStateOptions.Bird.BirdStupid, 1);
        level12.put(0, PlayStateOptions.Bird.BirdFire2, 3);
        level12.put(0, PlayStateOptions.Bird.Bird2, 3);
        level12.put(0, PlayStateOptions.Bird.FastBird2, 3);
        level12.put(0, PlayStateOptions.Bird.BirdTeleport, 6);
        level12.put(1, PlayStateOptions.Bird.BirdFire, 10);
        level12.put(1, PlayStateOptions.Bird.BirdZerg, 6);
        level12.put(1, PlayStateOptions.Bird.BirdTeleport, 5);
        level12.put(1, PlayStateOptions.Bird.Bird, 10);
        level12.put(1, PlayStateOptions.Bird.SlowBird, 3);
        level12.put(1, PlayStateOptions.Bird.SprintBird, 10);
        level12.put(1, PlayStateOptions.Bird.BirdStupid, 1);
        level12.put(1, PlayStateOptions.Bird.BirdFire2, 5);
        level12.put(1, PlayStateOptions.Bird.FastBird, 3);
        level12.put(1, PlayStateOptions.Bird.Bird2, 2);
        level12.put(1, PlayStateOptions.Bird.BirdHealer, 3);
        level12.put(1, PlayStateOptions.Bird.BirdTeleport, 10);
        level12.put(1, PlayStateOptions.Bird.BirdZerg2, 10);
        level12.put(1, PlayStateOptions.Bird.BirdAngry, 7);
        level12.put(2, PlayStateOptions.Bird.BirdTeleport, 5);
        level12.put(2, PlayStateOptions.Bird.BirdZerg, 5);
        level12.put(2, PlayStateOptions.Bird.BirdAngry, 2);
        level12.put(2, PlayStateOptions.Bird.Boss4, 1);
        levels[11] = level12;

        level13 = new PlayStateOptions(3,13);
        level13.put(0, PlayStateOptions.Bird.Bird, 13);
        level13.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level13.put(0, PlayStateOptions.Bird.BirdFire, 13);
        level13.put(0, PlayStateOptions.Bird.BirdStupid, 1);
        level13.put(0, PlayStateOptions.Bird.Bird2, 3);
        level13.put(0, PlayStateOptions.Bird.FastBird, 3);
        level13.put(0, PlayStateOptions.Bird.SprintBird, 2);
        level13.put(0, PlayStateOptions.Bird.BirdTeleport, 3);
        level13.put(1, PlayStateOptions.Bird.BirdAngry, 3);
        level13.put(1, PlayStateOptions.Bird.BirdSuicide, 3);
        level13.put(1, PlayStateOptions.Bird.Bird, 10);
        level13.put(1, PlayStateOptions.Bird.BirdTeleport, 3);
        level13.put(1, PlayStateOptions.Bird.BirdZerg, 3);
        level13.put(1, PlayStateOptions.Bird.BirdHealer, 3);
        level13.put(1, PlayStateOptions.Bird.SprintBird, 3);
        level13.put(1, PlayStateOptions.Bird.BirdStupid, 1);
        level13.put(1, PlayStateOptions.Bird.Bird2, 3);
        level13.put(1, PlayStateOptions.Bird.BirdFire, 3);
        level13.put(2, PlayStateOptions.Bird.BirdSuicide, 4);
        level13.put(2, PlayStateOptions.Bird.BirdTeleport, 6);
        level13.put(2, PlayStateOptions.Bird.BirdZerg, 8);
        level13.put(2, PlayStateOptions.Bird.BirdStupid, 1);
        level13.put(2, PlayStateOptions.Bird.Bird, 3);
        level13.put(2, PlayStateOptions.Bird.BirdFire, 3);
        level13.put(2, PlayStateOptions.Bird.FastBird, 3);
        level13.put(2, PlayStateOptions.Bird.BirdAngry, 3);
        level13.put(2, PlayStateOptions.Bird.BirdHealer, 6);
        levels[12] = level13;

        level14 = new PlayStateOptions(3,14);
        level14.put(0, PlayStateOptions.Bird.Bird, 10);
        level14.put(0, PlayStateOptions.Bird.BirdFire, 10);
        level14.put(0, PlayStateOptions.Bird.SlowBird, 2);
        level14.put(0, PlayStateOptions.Bird.FastBird, 10);
        level14.put(0, PlayStateOptions.Bird.BirdStupid, 1);
        level14.put(0, PlayStateOptions.Bird.BirdFire2, 3);
        level14.put(0, PlayStateOptions.Bird.FastBird2, 3);
        level14.put(0, PlayStateOptions.Bird.SprintBird, 10);
        level14.put(0, PlayStateOptions.Bird.BirdTeleport, 10);
        level14.put(0, PlayStateOptions.Bird.Boss1, 1);
        level14.put(1, PlayStateOptions.Bird.Boss2, 1);
        level14.put(1, PlayStateOptions.Bird.Bird, 4);
        level14.put(1, PlayStateOptions.Bird.SlowBird, 3);
        level14.put(1, PlayStateOptions.Bird.BirdFire, 4);
        level14.put(1, PlayStateOptions.Bird.FastBird, 4);
        level14.put(1, PlayStateOptions.Bird.BirdStupid, 2);
        level14.put(1, PlayStateOptions.Bird.Bird2, 2);
        level14.put(1, PlayStateOptions.Bird.BirdFire2, 2);
        level14.put(1, PlayStateOptions.Bird.FastBird2, 2);
        level14.put(1, PlayStateOptions.Bird.SprintBird, 2);
        level14.put(1, PlayStateOptions.Bird.BirdZerg, 4);
        level14.put(1, PlayStateOptions.Bird.BirdTeleport, 4);
        level14.put(1, PlayStateOptions.Bird.BirdHealer, 4);
        level14.put(2, PlayStateOptions.Bird.BirdSuicide, 4);
        level14.put(2, PlayStateOptions.Bird.BirdFire, 13);
        level14.put(2, PlayStateOptions.Bird.BirdAngry, 4);
        level14.put(2, PlayStateOptions.Bird.BirdZerg, 4);
        level14.put(2, PlayStateOptions.Bird.BirdTeleport, 4);
        level14.put(2, PlayStateOptions.Bird.BirdHealer, 4);
        level14.put(2, PlayStateOptions.Bird.Boss3, 1);
        levels[13] = level14;

        level15 = new PlayStateOptions(5,15);
        level15.put(0, PlayStateOptions.Bird.Bird, 10);
        level15.put(0, PlayStateOptions.Bird.BirdFire, 10);
        level15.put(0, PlayStateOptions.Bird.SprintBird, 10);
        level15.put(0, PlayStateOptions.Bird.BirdStupid, 1);
        level15.put(0, PlayStateOptions.Bird.Bird2, 5);
        level15.put(0, PlayStateOptions.Bird.SlowBird, 3);
        level15.put(0, PlayStateOptions.Bird.FastBird, 3);
        level15.put(0, PlayStateOptions.Bird.Bird3, 3);
        level15.put(0, PlayStateOptions.Bird.Boss1, 1);
        level15.put(1, PlayStateOptions.Bird.BirdStupid, 1);
        level15.put(1, PlayStateOptions.Bird.Bird, 3);
        level15.put(1, PlayStateOptions.Bird.BirdFire, 3);
        level15.put(1, PlayStateOptions.Bird.FastBird, 3);
        level15.put(1, PlayStateOptions.Bird.BirdFire2, 2);
        level15.put(1, PlayStateOptions.Bird.BirdSuicide, 4);
        level15.put(1, PlayStateOptions.Bird.Bird2, 10);
        level15.put(1, PlayStateOptions.Bird.BirdHealer, 4);
        level15.put(1, PlayStateOptions.Bird.BirdZerg, 6);
        level15.put(1, PlayStateOptions.Bird.BirdTeleport, 4);
        level15.put(1, PlayStateOptions.Bird.Boss2, 1);
        level15.put(2, PlayStateOptions.Bird.BirdFire, 5);
        level15.put(2, PlayStateOptions.Bird.BirdAngry, 5);
        level15.put(2, PlayStateOptions.Bird.SprintBird, 5);
        level15.put(2, PlayStateOptions.Bird.BirdTeleport, 5);
        level15.put(2, PlayStateOptions.Bird.BirdZerg, 8);
        level15.put(2, PlayStateOptions.Bird.BirdHealer, 5);
        level15.put(2, PlayStateOptions.Bird.Boss3, 1);
        level15.put(3, PlayStateOptions.Bird.SlowBird, 3);
        level15.put(3, PlayStateOptions.Bird.Bird, 20);
        level15.put(3, PlayStateOptions.Bird.BirdSuicide, 4);
        level15.put(3, PlayStateOptions.Bird.BirdTeleport, 10);
        level15.put(3, PlayStateOptions.Bird.SprintBird, 20);
        level15.put(3, PlayStateOptions.Bird.BirdStupid, 3);
        level15.put(3, PlayStateOptions.Bird.BirdFire, 15);
        level15.put(3, PlayStateOptions.Bird.BirdAngry, 7);
        level15.put(3, PlayStateOptions.Bird.FastBird, 4);
        level15.put(3, PlayStateOptions.Bird.BirdHealer, 8);
        level15.put(3, PlayStateOptions.Bird.BirdZerg, 10);
        level15.put(3, PlayStateOptions.Bird.Boss4, 1);
        level15.put(4, PlayStateOptions.Bird.Boss5, 1);
        levels[14] = level15;
    }

    public PlayStateOptions[] getLevels(){
        return levels;
    }

    public PlayStateOptions getLevelOptions(int levelNumber){
        return levels[levelNumber-1];
    }

}
